'use client'

import { useState, useRef, useEffect } from 'react'
import { X, Send } from 'lucide-react'
import { api, type ChatMessage } from '@/lib/api'

interface ChatDrawerProps { isOpen: boolean; onClose: () => void; repoId: string; repoName: string }
const suggestedQuestions = ['What does this repo do?', "What's the riskiest recent change?", 'Explain the folder structure']

export function ChatDrawer({ isOpen, onClose, repoId, repoName }: ChatDrawerProps) {
  const [messages, setMessages] = useState<ChatMessage[]>([]); const [input, setInput] = useState(''); const [isLoading, setIsLoading] = useState(false); const [error, setError] = useState(''); const messagesEndRef = useRef<HTMLDivElement>(null); const inputRef = useRef<HTMLInputElement>(null)
  useEffect(() => { if (isOpen) { inputRef.current?.focus(); api.getChatHistory(repoId).then(setMessages).catch((err: unknown) => setError(err instanceof Error ? err.message : 'Could not load chat history')) } }, [isOpen, repoId])
  useEffect(() => messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' }), [messages, isLoading])
  const send = async (text = input) => { if (!text.trim() || isLoading) return; const message = text.trim(); const optimistic: ChatMessage = { id: Date.now(), role: 'user', content: message, created_at: new Date().toISOString() }; setMessages((current) => [...current, optimistic]); setInput(''); setIsLoading(true); setError(''); try { const result = await api.sendChatMessage(repoId, message); setMessages((current) => [...current, { id: Date.now() + 1, role: 'assistant', content: result.response, created_at: new Date().toISOString() }]) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to send message') } finally { setIsLoading(false) } }
  return <>{isOpen && <div className="fixed inset-0 bg-black/50 z-40 transition-opacity" onClick={onClose} />}<div className={`fixed right-0 top-0 h-full w-full max-w-md bg-background border-l border-border flex flex-col z-50 transition-transform duration-300 ${isOpen ? 'translate-x-0' : 'translate-x-full'}`}><div className="border-b border-border px-6 py-4 flex items-center justify-between"><div><p className="text-xs text-muted uppercase tracking-widest mb-1">Repository</p><h3 className="text-foreground font-medium">{repoName}</h3></div><button onClick={onClose} className="p-2 hover:bg-card rounded-lg transition-colors text-muted hover:text-foreground" aria-label="Close chat"><X className="w-5 h-5" /></button></div><div className="flex-1 overflow-y-auto px-6 py-6 space-y-4">{messages.length === 0 ? <div className="h-full flex flex-col items-center justify-center text-center"><p className="text-xs text-muted uppercase tracking-widest mb-4">Ask Anything</p><h4 className="text-lg font-light text-foreground mb-6">Chat with this repo</h4><div className="space-y-2 w-full">{suggestedQuestions.map((question) => <button key={question} onClick={() => send(question)} className="w-full px-4 py-2.5 rounded-lg border border-border text-foreground text-sm hover:bg-card transition-colors text-left">{question}</button>)}</div></div> : messages.map((message) => <div key={message.id} className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-xs px-4 py-2.5 rounded-lg text-sm whitespace-pre-wrap ${message.role === 'user' ? 'bg-primary text-primary-foreground' : 'bg-card border border-border text-foreground'}`}>{message.content}</div></div>)}{isLoading && <p className="text-sm text-muted">RepoLens is thinking…</p>}{error && <p className="text-sm text-red-400">{error}</p>}<div ref={messagesEndRef} /></div><div className="border-t border-border px-6 py-4"><div className="flex gap-2"><input ref={inputRef} type="text" value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && send()} placeholder="Ask something..." disabled={isLoading} className="flex-1 px-4 py-2 rounded-full bg-card border border-border text-foreground placeholder-muted focus:outline-none focus:ring-2 focus:ring-primary transition-all disabled:opacity-50" /><button onClick={() => send()} disabled={!input.trim() || isLoading} className="p-2 rounded-full bg-primary text-primary-foreground hover:opacity-90 disabled:opacity-50" aria-label="Send message"><Send className="w-5 h-5" /></button></div></div></div></>
}
